### ISSUE TITLE
Issue when creating qa (RetrievalQA.from_chain_type.....)

### ISSUE THREAD

**Issue by Chai1237** [ksmin23/rag-with-amazon-opensearch#1]
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[173], line 14
     10 qa_prompt = PromptTemplate(template=template, input_variables=["context","question"])
     12 chain_type_kwargs = { "prompt": qa_prompt, "verbose": False } # change verbose to True if you need to see what's happening
---> 14 qa = RetrievalQA.from_chain_type(
     15     llm=bedrock_llm, 
     16     chain_type="stuff", 
     17     retriever=retriever,
     18     chain_type_kwargs=chain_type_kwargs,
     19     verbose=True # change verbose to True if you need to see what's happening
     20 )
     21 question = "List out oil palm tree planted area for each state in Malaysia."
     22 result = qa.run(question)

File /opt/conda/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py:103, in BaseRetrievalQA.from_chain_type(cls, llm, chain_type, chain_type_kwargs, **kwargs)
     99 _chain_type_kwargs = chain_type_kwargs or {}
    100 combine_documents_chain = load_qa_chain(
    101     llm, chain_type=chain_type, **_chain_type_kwargs
    102 )
--> 103 return cls(combine_documents_chain=combine_documents_chain, **kwargs)

File /opt/conda/lib/python3.10/site-packages/langchain/load/serializable.py:97, in Serializable.__init__(self, **kwargs)
     96 def __init__(self, **kwargs: Any) -> None:
---> 97     super().__init__(**kwargs)
     98     self._lc_kwargs = kwargs

File /opt/conda/lib/python3.10/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for RetrievalQA
retriever
  Can't instantiate abstract class BaseRetriever with abstract method _get_relevant_documents (type=type_error)
  
  
  
  
  Is there any solution for this error?

**Comment by ksmin23** [comment]
I think you need to check if the version of the LangChain is the right one. 
The Streamit application int this project is using `LangChain 0.0.219`.

**Comment by Chai1237** [comment]
Hi just realised I imported OpenSearchVectorSearch from langchain_community.vectorstores, after I changed it to langchain.vectorstores everything works. Thank you
